# Generated by Django 4.0.5 on 2023-10-29 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_userprofile_city_userprofile_farm_userprofile_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmname', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('typeofcrop', models.CharField(max_length=200)),
                ('startdate', models.CharField(max_length=200)),
                ('enddate', models.CharField(max_length=200)),
                ('yieldtons', models.CharField(max_length=200)),
                ('totalarea', models.CharField(max_length=200)),
                ('totalproduction', models.CharField(max_length=200)),
                ('totalcrops', models.CharField(max_length=200)),
                ('soilcondition', models.CharField(max_length=200)),
                ('disease', models.CharField(max_length=200)),
                ('diseasepercentage', models.CharField(max_length=200)),
                ('yieldpercentage', models.CharField(max_length=200)),
                ('waterlevel', models.CharField(max_length=200)),
                ('income', models.CharField(max_length=200)),
                ('expenses', models.CharField(max_length=200)),
                ('farmprofit', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField()),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.statistics')),
            ],
        ),
    ]
